export { default as en } from './en.json'
export { default as es } from './es.json'
export { default as fr } from './fr.json'
export { default as ko } from './ko.json'
export { default as zh } from './zh.json'
