name: Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  node:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: installing npm
        run: npm i -g npm@10

      - name: installing
        run: npm ci --audit false --fund false

      - name: linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_extensions: ts,tsx,js,jsx
          eslint_dir: src/
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: testing
        run: npm test -- --coverage

      - name: coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: building
        run: npm run build
